# Generated by Django 3.2.6 on 2022-03-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загловок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
