# Generated by Django 3.2.6 on 2022-03-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_apps', '0002_auto_20220310_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
