# Generated by Django 3.2.9 on 2022-08-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_apps', '0005_auto_20220820_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
    ]
