# Generated by Django 3.2.9 on 2022-08-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_apps', '0006_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загловок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Картинка')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
